import { powerlink } from "../core/powerlink";
import { InferGetServerSidePropsType, NextApiResponse } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Select from "react-select";

type Data = {
  pk: string | undefined;
  ambs: Array<{ value: string; label: string }>;
  campaign: string;
  amb: string | null;
};

export const getServerSideProps = async ({
  res,
  query,
}: {
  res: NextApiResponse;
  query: Record<string, string>;
}) => {
  const data: Data = {
    amb: query.amb ?? null,
    pk: process.env.STRIPE_PK,
    campaign: query.id ?? "177b5cd5-2a69-4933-992e-1dd3599eb77e",
    ambs: await powerlink(
      query.id ?? "177b5cd5-2a69-4933-992e-1dd3599eb77e",
      query.amb
    ),
  };
  return { props: { data } };
};

function Home({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const [multiSub, setMultiSub] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        dir="rtl"
        id="donation-form"
        action="/api/create-session"
        method="post"
        className="rounded-lg bg-white p-6"
      >
        <h2 className="mb-4 text-lg font-medium">טופס תרומה</h2>
        <input type="hidden" name="campaign" value={data.campaign} />
        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">שגריר</label>
          {data.amb ? (
            <>
              <input
                value={data.ambs[0]?.label}
                readOnly
                className="w-full rounded-lg border border-gray-400 p-2"
              />
              <input name="amb" value={data.ambs[0]?.value} hidden readOnly />
            </>
          ) : (
            <Select
              options={data.ambs as any}
              defaultValue=""
              className="w-full rounded-lg"
              name="amb"
            />
          )}
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">
            שם מלא <span className="text-red-700">*</span>
          </label>
          <input
            required
            className="w-full rounded-lg border border-gray-400 p-2"
            type="text"
            name="full_name"
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">
            דואר אלקטרוני
          </label>
          <input
            className="w-full rounded-lg border border-gray-400 p-2"
            type="email"
            name="email"
            placeholder="כתוב את כתובת הדואר האלקטרוני שלך"
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">
            טלפון נייד
          </label>
          <input
            className="w-full rounded-lg border border-gray-400 p-2"
            type="tel"
            name="phone"
            placeholder="כתוב את מספר הטלפון הנייד שלך"
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">כתובת</label>
          <input
            className="w-full rounded-lg border border-gray-400 p-2"
            type="text"
            name="address"
            placeholder=""
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">עיר</label>
          <input
            className="w-full rounded-lg border border-gray-400 p-2"
            type="text"
            name="city"
            placeholder=""
          />
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">סכום</label>
          <div className="flex">
            <input
              className="w-full rounded-r-lg border border-gray-400 p-2"
              type="number"
              name="amount"
              min={1}
              placeholder="כתוב את הסכום של התרומה"
              required
            />

            <div className="flex items-center justify-center rounded-l-lg border border-r-0 border-gray-400  bg-gray-400 px-3 text-lg text-white">
              $
            </div>
          </div>
        </div>

        <div className="mb-4 flex justify-start">
          <input
            className=" rounded-lg border border-gray-400"
            type="checkbox"
            name="multiSub"
            checked={multiSub}
            onChange={() => setMultiSub((prev) => !prev)}
          />
          <label className="mx-2 block font-medium text-gray-700">
            תרומה חוזרת
          </label>
        </div>

        {multiSub ? (
          <div className="mb-4">
            <label className="mb-2 block font-medium text-gray-700">
              מספר תרומות
            </label>

            <div className="flex">
              <select
                className="w-full rounded-lg border border-gray-400 p-2"
                name="months"
                id="contributions"
                required
                defaultValue={12}
              >
                {/* <option value="no limit">ללא הגבלה</option> */}
                {new Array(24).fill(0).map((_, i) => (
                  <option value={i + 1} key={i + 1}>
                    {i + 1}
                  </option>
                ))}
              </select>
            </div>
          </div>
        ) : (
          <input type="hidden" name="months" value={1} />
        )}

        <div className="mb-4 flex justify-start">
          <input
            className=" rounded-lg border border-gray-400"
            type="checkbox"
            name="anonymous"
          />
          <label className="mx-2 block font-medium text-gray-700">
            תרומה אנונימית
          </label>
        </div>

        <div className="mb-4">
          <label className="mb-2 block font-medium text-gray-700">הקדשה</label>
          <textarea
            className="h-36 w-full rounded-lg border border-gray-400 p-2"
            name="dedication"
          />
        </div>

        <button className="w-full rounded-lg bg-indigo-500 py-2 px-4 text-white hover:bg-indigo-600">
          תרום
        </button>
      </form>
    </>
  );
}

export default Home;
